repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        exclude: ^templates/.*\.html$

  - repo: local
    hooks:
      - id: social-cards
        name: Generate Zola Social Cards
        entry: bash -c 'for x in "$@"; do .pre-commit-hooks/social-cards-zola.sh --output-path static/imgs/social-cards --base-url http://127.0.0.1:1111 --update-front-matter --print-output --input "$x"; done' --
        language: system
        files: ^content/blog/.*\.md$
